apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fpga-reader
rules:
- apiGroups: ["fpga.intel.com"]
  resources: ["acceleratorfunctions", "fpgaregions"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-fpga-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fpga-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {namespace}
