apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mlu100-plugin
  namespace: kube-system
  labels:
    app: mlu100-plugin
spec:
  selector:
    matchLabels:
      app: mlu100-plugin
  template:
    metadata:
      labels:
        app: mlu100-plugin
    spec:
      containers:
      - name: mlu100-plugin
        env:
          - name: archlab-sys-7048gr-tr
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: intel-gpu-plugin:devel
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: devfs
          mountPath: /dev
        - name: sysfs
          mountPath: /sys
        - name: kubeletsockets
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: sysfs
        hostPath:
          path: /sys
      - name: kubeletsockets
        hostPath:
          path: /var/lib/kubelet/device-plugins
